// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: workflowsgrpc/events.proto

package workflowsgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrpcEventMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Function      string                 `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	Node          string                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Workflow      string                 `protobuf:"bytes,3,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Server        string                 `protobuf:"bytes,5,opt,name=server,proto3" json:"server,omitempty"`
	Event         string                 `protobuf:"bytes,6,opt,name=event,proto3" json:"event,omitempty"`
	Text          string                 `protobuf:"bytes,7,opt,name=text,proto3" json:"text,omitempty"`
	Run           string                 `protobuf:"bytes,8,opt,name=run,proto3" json:"run,omitempty"`
	Meta          *structpb.Struct       `protobuf:"bytes,9,opt,name=meta,proto3" json:"meta,omitempty"`
	Payload       []byte                 `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`
	CorrelationId string                 `protobuf:"bytes,11,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcEventMessage) Reset() {
	*x = GrpcEventMessage{}
	mi := &file_workflowsgrpc_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcEventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcEventMessage) ProtoMessage() {}

func (x *GrpcEventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_workflowsgrpc_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcEventMessage.ProtoReflect.Descriptor instead.
func (*GrpcEventMessage) Descriptor() ([]byte, []int) {
	return file_workflowsgrpc_events_proto_rawDescGZIP(), []int{0}
}

func (x *GrpcEventMessage) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *GrpcEventMessage) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *GrpcEventMessage) GetWorkflow() string {
	if x != nil {
		return x.Workflow
	}
	return ""
}

func (x *GrpcEventMessage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GrpcEventMessage) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *GrpcEventMessage) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *GrpcEventMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GrpcEventMessage) GetRun() string {
	if x != nil {
		return x.Run
	}
	return ""
}

func (x *GrpcEventMessage) GetMeta() *structpb.Struct {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GrpcEventMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GrpcEventMessage) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

var File_workflowsgrpc_events_proto protoreflect.FileDescriptor

const file_workflowsgrpc_events_proto_rawDesc = "" +
	"\n" +
	"\x1aworkflowsgrpc/events.proto\x12\tworkflows\x1a\x1cgoogle/protobuf/struct.proto\"\xba\x02\n" +
	"\x10GrpcEventMessage\x12\x1a\n" +
	"\bfunction\x18\x01 \x01(\tR\bfunction\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\x12\x1a\n" +
	"\bworkflow\x18\x03 \x01(\tR\bworkflow\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x16\n" +
	"\x06server\x18\x05 \x01(\tR\x06server\x12\x14\n" +
	"\x05event\x18\x06 \x01(\tR\x05event\x12\x12\n" +
	"\x04text\x18\a \x01(\tR\x04text\x12\x10\n" +
	"\x03run\x18\b \x01(\tR\x03run\x12+\n" +
	"\x04meta\x18\t \x01(\v2\x17.google.protobuf.StructR\x04meta\x12\x18\n" +
	"\apayload\x18\n" +
	" \x01(\fR\apayload\x12%\n" +
	"\x0ecorrelation_id\x18\v \x01(\tR\rcorrelationId2V\n" +
	"\fEventService\x12F\n" +
	"\x06Events\x12\x1b.workflows.GrpcEventMessage\x1a\x1b.workflows.GrpcEventMessage(\x010\x01B\x1fZ\x1d./workflowsgrpc;workflowsgrpcb\x06proto3"

var (
	file_workflowsgrpc_events_proto_rawDescOnce sync.Once
	file_workflowsgrpc_events_proto_rawDescData []byte
)

func file_workflowsgrpc_events_proto_rawDescGZIP() []byte {
	file_workflowsgrpc_events_proto_rawDescOnce.Do(func() {
		file_workflowsgrpc_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflowsgrpc_events_proto_rawDesc), len(file_workflowsgrpc_events_proto_rawDesc)))
	})
	return file_workflowsgrpc_events_proto_rawDescData
}

var file_workflowsgrpc_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_workflowsgrpc_events_proto_goTypes = []any{
	(*GrpcEventMessage)(nil), // 0: workflows.GrpcEventMessage
	(*structpb.Struct)(nil),  // 1: google.protobuf.Struct
}
var file_workflowsgrpc_events_proto_depIdxs = []int32{
	1, // 0: workflows.GrpcEventMessage.meta:type_name -> google.protobuf.Struct
	0, // 1: workflows.EventService.Events:input_type -> workflows.GrpcEventMessage
	0, // 2: workflows.EventService.Events:output_type -> workflows.GrpcEventMessage
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_workflowsgrpc_events_proto_init() }
func file_workflowsgrpc_events_proto_init() {
	if File_workflowsgrpc_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflowsgrpc_events_proto_rawDesc), len(file_workflowsgrpc_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workflowsgrpc_events_proto_goTypes,
		DependencyIndexes: file_workflowsgrpc_events_proto_depIdxs,
		MessageInfos:      file_workflowsgrpc_events_proto_msgTypes,
	}.Build()
	File_workflowsgrpc_events_proto = out.File
	file_workflowsgrpc_events_proto_goTypes = nil
	file_workflowsgrpc_events_proto_depIdxs = nil
}
